# Generated by Django 4.1.5 on 2023-03-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
    ]
